services:
  - type: web
    name: note-taking-backend
    env: java
    rootDir: BE
    buildCommand: chmod +x mvnw && ./mvnw clean install
    startCommand: chmod +x mvnw && ./mvnw spring-boot:run
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/java
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-cvil8295pdvs738p8590-a:5432/note_taking
      - key: SPRING_DATASOURCE_USERNAME
        value: note_taking_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: MQbCxBrioO7J6R1FqR5DWs3FK5FLwHtI